import type { SandboxProvider } from '@/lib/sandbox/types';
import type { Snapshot } from './store';

// Files / directories to skip during snapshot. Anything generated, cached,
// or huge.
const EXCLUDES = [
  './node_modules/*',
  './.git/*',
  './.next/*',
  './dist/*',
  './build/*',
  './.cache/*',
  './.turbo/*',
];

// Recursively enumerate text files in the sandbox project root via `find`.
// This is more reliable than recursively calling listFiles() across whatever
// directory tree the agent built.
async function listProjectFiles(sandbox: SandboxProvider): Promise<string[]> {
  const notPath = EXCLUDES.map((p) => `-not -path '${p}'`).join(' ');
  const cmd = `find . -type f ${notPath} -not -name '.DS_Store' -not -name '*.log'`;
  const result = await sandbox.runCommand(cmd);
  if (!result.success) {
    throw new Error(`snapshot find failed: ${result.stderr || result.stdout}`);
  }
  return result.stdout
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.startsWith('./'))
    .map((l) => l.replace(/^\.\//, ''));
}

// Some files are big or binary-ish — skip to keep snapshots lean. The Vite
// dev environment writes package-lock.json which we KEEP because the agent
// may have added deps and we want a deterministic restore.
const SKIP_PATTERNS = [
  /\.(png|jpg|jpeg|gif|webp|svg|ico|woff|woff2|ttf|eot|mp3|mp4|webm|zip|tar|gz)$/i,
];

// Hard cap per file (1MB). Beyond this we skip — typically only lockfiles
// and they get regenerated by npm install anyway.
const MAX_FILE_BYTES = 1_024 * 1_024;

export async function snapshotProject(sandbox: SandboxProvider): Promise<Snapshot> {
  const paths = await listProjectFiles(sandbox);
  const files: Snapshot['files'] = [];
  let totalBytes = 0;

  for (const p of paths) {
    if (SKIP_PATTERNS.some((rx) => rx.test(p))) continue;
    let content: string;
    try {
      content = await sandbox.readFile(p);
    } catch (err) {
      // File appeared in find but vanished by the time we read it — skip.
      console.warn('[snapshot] could not read', p, err);
      continue;
    }
    const bytes = Buffer.byteLength(content, 'utf8');
    if (bytes > MAX_FILE_BYTES) {
      console.warn(`[snapshot] skipping ${p} (${bytes} bytes > cap)`);
      continue;
    }
    files.push({ path: p, content });
    totalBytes += bytes;
  }

  return {
    version: 1,
    files,
    meta: {
      capturedAt: new Date().toISOString(),
      fileCount: files.length,
      totalBytes,
    },
  };
}

// Restore a snapshot into a sandbox: writes each file back, then runs
// `npm install` if package.json was included. Returns once the dev server
// should be picking up changes again.
export async function restoreProject(
  sandbox: SandboxProvider,
  snapshot: Snapshot,
): Promise<void> {
  for (const f of snapshot.files) {
    try {
      await sandbox.writeFile(f.path, f.content);
    } catch (err) {
      console.error('[restore] writeFile failed for', f.path, err);
      throw err;
    }
  }

  const hasPackageJson = snapshot.files.some((f) => f.path === 'package.json');
  if (hasPackageJson) {
    // Use the provider's installPackages with an empty array to trigger
    // `npm install` if supported, otherwise fall back to a raw command.
    const result = await sandbox.runCommand('npm install --no-audit --no-fund');
    if (!result.success) {
      console.warn('[restore] npm install non-zero exit:', result.stderr.slice(0, 500));
    }
  }
}
